### ISSUE TITLE
release 4.5.1

### ISSUE THREAD

**Issue by jangalinski** [holixon/axon-framework-bom#13]

**Comment by jangalinski** [comment]
`mvn gitflow:release-finish` Did not work

```
Prepare maven setings: /home/runner/.m2/settings.xml
10
Error: Unexpected token # in JSON at position 80
11
SyntaxError: Unexpected token # in JSON at position 80
12
    at JSON.parse (<anonymous>)
13
    at Object.fillServers (/home/runner/work/_actions/s4u/maven-settings-action/v1/settings.js:35:10)
14
    at run (/home/runner/work/_actions/s4u/maven-settings-action/v1/index.js:22:14)
15
    at Object.<anonymous> (/home/runner/work/_actions/s4u/maven-settings-action/v1/index.js:33:1)
16
    at Module._compile (internal/modules/cjs/loader.js:959:30)
17
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
18
    at Module.load (internal/modules/cjs/loader.js:815:32)
19
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
20
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
21
    at internal/main/run_main_module.js:17:11

**Comment by zambrovski** [comment]
Fixed with https://github.com/holixon/axon-framework-bom/runs/2692574962
